### ISSUE TITLE
SnackBar and Modal

### ISSUE THREAD

**Issue by Kaishley** [9gag-open-source/react-native-snackbar-dialog#21]
Currently, when using a Modal, SnackBar dialogs display behind the Modal.

Is there any way of having the SnackBar display on top of the Modal?

I tried changing the zIndex of the SnackBar, which had no effect.

**Comment by georgejor** [comment]
Which modal library are you using now?

It is somehow not possible to formally do z ordering for two position absolute elements appear together for iOS. But there is a props `evaluation` for Android 5 or more, see https://facebook.github.io/react-native/docs/view.html#style .

Instead, you could workaround like:
- Handle the display ordering, either the callback from this library or from the modal lib (ideal)
- Toggle `flex: 1` or `left: 0; right: 0` under position absolute element

**Comment by Kaishley** [comment]
I am using the Modal Component from RN itself due to its great native performance.

I'll try to see if there are any workarounds.

**Comment by raynor85** [comment]
I have created a modal wrapper which allows you to use both the react native modal component and a javascript version of it. Feel free to check it out. https://github.com/raynor85/react-native-modal-wrapper

**Comment by georgejor** [comment]
https://github.com/9gag-open-source/react-native-snackbar-dialog/issues/21#issuecomment-290619834

If you have better findings, please do let us know.
