### ISSUE TITLE
Too tall in height?

### ISSUE THREAD

**Issue by eddnav** [9gag-open-source/react-native-snackbar-dialog#22]
![image](https://cloud.githubusercontent.com/assets/4434924/24633671/b3f4640a-1897-11e7-850d-006c4f156a2a.png)

Setting padding to 0 doesn't change anything, changing the height cuts off the text, did I miss something?

**Comment by eddnav** [comment]
This only seems to happen if I have a button text configured, is there no way to get an inline snackbar with a button?

**Comment by eddnav** [comment]
https://github.com/9gag-open-source/react-native-snackbar-dialog/blob/master/src/SnackBar.js#L80

That padding seems to be the problem, it's a trivial change, but I could add a pull request nonetheless. Is that padding ever expected for anything else? it does seem to be targeted on inline specifically...

**Comment by georgejor** [comment]
@eddnav Yes, you are right. You are welcomed to make a PR that allows overriding the default inline row padding in order to make a more flexible styling.
